users = read.csv('data/user_data.csv',
                 header=F,
                 col.names=c('id', 
                             'dorm_id', 
                             'class_year_id', 
                             'gender_id', 
                             'match_with_id', 
                             'created_at', 
                             'dating'))

prior.wlng = read.csv('data/prior_willingness.csv',
                      header=F,
                      col.names=c('user_id', 'answer_id'))
post.wlng = read.csv('data/posterior_willingness.csv',
                     header=F,
                     col.names=c('u1_id', 'u2_id', 'u1_willing', 'u2_willing'))

user.personality = na.omit(read.csv('data/user_personality.csv',
                                    header=F,
                                    col.names=c('id',
                                               'ambitious',
                                               'cynical',
                                               'athletic',
                                               'kinky',
                                               'nerdy',
                                               'cultured',
                                               'political',
                                               'romantic',
                                               'social',
                                               'twisted',
                                               'creative',
                                               'boring',
                                               'matchready',
                                               'age',
                                               'house',
                                               'oncampus')))