source('config.R')

source('model_explicit_eagerness.R')
source('model_latent_eagerness.R')
source('model_personality.R')
source('model_proximity.R')
source('model_sexuality.R')
source('model_suggestion.R')
source('model_truth.R')
source('model_null.R')

load('data/model_best.RData')
load('data/model_inherent.RData')
load('data/model_base_BIC.RData')
load('data/model_base_AIC.RData')